### ISSUE TITLE
Admin Menus

### ISSUE THREAD

**Issue by ZombiEquinox** [epferrari/mkapp#1]
Admin did not come with any default menu items, when creating a menuItems array and adding menuItems={menuItems} onto AppNav i get the error:

> Uncaught TypeError: Cannot read property 'getTypekit' of undefined

when scanning the MKAPP directory for getTypekit, it is usually attached to mkappTheme, so I added mkappTheme onto childContextType, imported MkappTheme, bascially all the same things from Public view for theming and menuItems. I continue to receive the same error. 

is there something missing from the Admin side I need to add on for menuItems? Or is menu for Admin currently not functional?

**Comment by epferrari** [comment]
Thanks for finding this. Just released patch 0.8.1 addressing this and a few other issues.

**Comment by epferrari** [comment]
Closing, let me know if you run into anything else
